resources:
  repositories:
  - repository: 1ESPipelineTemplates
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release

trigger:
  branches:
    include:
      - main
pr: none

parameters:
  - name: dotnet_configurations
    type: object
    default:
      - Release
  - name: buildPlatforms
    type: object
    default:
      - x64
      - arm64
  - name: pools
    type: object
    default:
    - name: Azure-Pipelines-1ESPT-ExDShared
      image: windows-latest
      os: windows
    - name: Azure-Pipelines-1ESPT-ExDShared
      image: ubuntu-latest
      os: linux
    - name: Azure Pipelines
      image: macos-latest
      os: macOS

name: 0.0.$(Date:yyMM).$(Date:dd)$(Rev:rr)

extends:
  template: v1/1ES.Unofficial.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    customBuildTags:
    - ES365AIMigrationTooling
    sdl:
      sourceAnalysisPool:
        name: Azure-Pipelines-1ESPT-ExDShared
        image: windows-2022
        os: windows
      credscan:
        suppressionsFile: '$(System.DefaultWorkingDirectory)/.pipelines/CredScanSuppressions.json'
      binSkim:
        AnalyzeTargetGlob: '$(System.DefaultWorkingDirectory)\MSStore.API\bin\**\net9.0\MSStore.API.dll'
    stages:
      - stage: Build_And_Run_CodeQL
        jobs:
        - ${{ each pool in parameters.pools }}:
          - ${{ each dotnet_config in parameters.dotnet_configurations }}:
            - job: Build_And_Run_CodeQL_${{ pool.os }}_${{ dotnet_config }}
              pool:
                name: ${{ pool.name }}
                image: ${{ pool.image }}
                os: ${{ pool.os }}
              steps:
              - checkout: self
              - task: UseDotNet@2
                displayName: Setup .NET 9
                inputs:
                  version: 9.0.x
              - script: mv -f $(Build.SourcesDirectory)/.pipelines/release-nuget.config ./nuget.config
                displayName: Add release package source
              - task: NuGetAuthenticate@1
              - script: dotnet restore MSStore.CLI.sln /p:Configuration=${{ dotnet_config }}
                displayName: Restore dependencies
              - template: ./.pipelines/templates/build-nuget.yaml@self
                parameters:
                  dotnet_configuration: ${{ dotnet_config }}
                  AgentOS: $(Agent.OS)
                  DoEsrp: false
                  signingIdentity: {}